### PR TITLE
Fix php8.1 deprecation error

### PR DESCRIPTION
**Pull request by asika32764**

### CODE REVIEW

**Comment by asika32764** [comment]
The error was caused by https://github.com/WyriHaximus/reactphp-child-process-messenger/blob/master/src/ChildInterface.php#L11

Must change return type to `mixed`

**Comment by WyriHaximus** [comment]
This might not be invalid after all, does the error you mention at https://github.com/WyriHaximus/reactphp-child-process-messenger/pull/79#issue-839954256 disappear when you add this line?

**Comment by asika32764** [comment]
`#[\ReturnTypeWillChange]` won't work, must remove `void` from the interface return type.

**Comment by WyriHaximus** [comment]
> `#[\ReturnTypeWillChange]` won't work, must remove `void` from the interface return type.

It is not there for the latest tagged version: https://github.com/WyriHaximus/reactphp-child-process-messenger/blob/4.0.2/src/ChildInterface.php#L16

**Comment by asika32764** [comment]
Close since the root library updated.

**Pull request closed without merging**
